org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=false

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.nonFinalResIds=true
kotlin.code.style=official
kotlin.incremental=true

# Compose compiler reports (optional)
# enableComposeCompilerReports=true

android.enableR8.fullMode=true
android.enableR8.libraries=true

# Target SDK
android.compileSdk=35
android.minSdk=26
android.targetSdk=35
