org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=false

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.nonFinalResIds=true
kotlin.code.style=official
kotlin.incremental=true

# Compose compiler reports (optional)
# enableComposeCompilerReports=true

android.enableR8.fullMode=true
android.enableR8.libraries=true

# Target SDK
android.compileSdk=35
android.minSdk=26
android.targetSdk=35
